### ISSUE TITLE
vocore2 ultimate does not boot after flashing uImage

### ISSUE THREAD

**Issue by jkimmel** [noblepepper/VoCore2-feed#1]
That's what I get:

`3: System Boot system code via Flash.
## Booting image at bc050000 ...
   Image Name:   MIPS OpenWrt Linux-3.18.45
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    1144857 Bytes =  1.1 MB
   Load Address: 80000000
   Entry Point:  80000000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
## Giving linux memsize in MB, 128

Starting kernel ...

[    0.000000] Linux version 3.18.45 (osboxes@osboxes) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r49404) ) #1 Thu Aug 10 13:33:58 BST 2017
[    0.000000] Board has DDR2
[    0.000000] Analog PMU set to hw control
[    0.000000] Digital PMU set to hw control
[    0.000000] SoC Type: MediaTek MT7628AN ver:1 eco:2
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019655 (MIPS 24KEc)
`

**Comment by noblepepper** [comment]
I only now noticed this, sorry for the delay. I hope you figured this out yourself but basically you flashed the wrong file to your VoCore2:
1. uImage is the kernel only, the system needs a file system to
2. the sysupgrade file has the kernel and the file system (initrd)
the message "No initrd" is the signal as to what is wrong.
